const fs = require('fs');
const path = require('path');

// Import the CSS variables generator
const { generateCSSVariables } = require('../dist/css-variables');

// Generate CSS variables
const cssVariables = generateCSSVariables();

// Create the CSS content
const cssContent = `/* 
 * Auto-generated CSS variables from design tokens
 * Do not edit this file directly - modify the tokens in src/tokens.ts
 */

:root {
  ${cssVariables}
}

/* Dark mode overrides (since this is dark-mode only) */
.dark {
  /* All variables are already dark mode optimized */
}

/* Component-specific utility classes */
.bg-background-primary {
  background-color: var(--color-background-primary);
}

.bg-background-secondary {
  background-color: var(--color-background-secondary);
}

.bg-background-tertiary {
  background-color: var(--color-background-tertiary);
}

.bg-surface-primary {
  background-color: var(--color-surface-primary);
}

.bg-surface-secondary {
  background-color: var(--color-surface-secondary);
}

.text-text-primary {
  color: var(--color-text-primary);
}

.text-text-secondary {
  color: var(--color-text-secondary);
}

.border-border-primary {
  border-color: var(--color-border-primary);
}

.border-border-focus {
  border-color: var(--color-border-focus);
}
`;

// Ensure the dist directory exists
const distDir = path.join(__dirname, '../dist');
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

// Write the CSS file
const cssPath = path.join(distDir, 'tokens.css');
fs.writeFileSync(cssPath, cssContent);

console.log(`✅ Generated CSS variables file: ${cssPath}`);
console.log(`📊 Generated ${Object.keys(cssVariables).length} CSS variables`);
